fix(object): No longer inherit from array
This is problematic as were overloading the types in various places:

error: Argument 1 of "__getitem__" incompatible with supertype "Array"